### PR TITLE
NYPL-148 docker update

### PR DESCRIPTION
**Pull request by datalogics-dans**
Addresses [NYPL-149](https://jira.datalogics.com/browse/NYPL-149) (subtask of NYPL-148).

Ultimately, we want to install the Circulation Manager using Docker _and_ EC2 Container Service. This PR does only the former, but it brings us much closer to the functionality we want compared to where it was before.

Also, note that the files in roles/simplye-docker/files were copied from roles/simplye-circulation/files without modification.

Further documentation on how this works, plus limitations, is here: https://wiki.datalogics.com/display/EN/Repeatable+Installation+Steps

### CODE REVIEW

**Comment by datalogics-cgreen** [comment]
I'm having trouble getting the CM started. It seems to be having trouble parsing the config file:

`core.config.CannotLoadConfiguration: Error loading configuration file /etc/circulation/config.json: No JSON object could be decoded`

The Ansible script managed to place my information in that config file, so I wonder what I might missing.

**Comment by datalogics-dans** [comment]
@datalogics-cgreen I've seen that error before, and I think it _might_ be a permissions issue. The Docker image uses a volume for the config: it's stored on the server at /home/ec2-user/config.json and inside the container at /etc/circulation/config.json. Make sure both exist, then check either one for basic syntax issues (commas and brackets, mostly).

I'm running it again myself to see if I can see the same problem.

**Comment by datalogics-cgreen** [comment]
@datalogics-dans So yes, as I indicated earlier today, I got the circulation manager deployed successfully. In light of the last commit, I'm okay with merging this now as long as you didn't need to add anything else (i.e., automating a few things); but, as it stands, it works (provided you don't miss an obvious comment or two like I did).

**Comment by datalogics-dans** [comment]
@datalogics-cgreen I've got nothing to add at the moment, so if the deployment worked in the end, you can merge anytime!

**Pull request merged**
